language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
  - phpunit

notifications:
  email: false
